### PR TITLE
A whole crap ton of tests :smile:

### PR DESCRIPTION
**Pull request by jmcdo29**
So, there's a ton of file additions and tests in this. Take your time going through them. The GitHub Actions workflow works again :rocket: :confetti_ball:

### CODE REVIEW

**Review by jeffminsungkim — APPROVED** [review]
Nice to see that you've removed if statements from `delegator.service.ts` that I've mentioned on Discord.
Everything looks good so far :) I'll make some additions after this commit has merged.

**Review by ruslanguns — APPROVED** [review]

**Comment by ruslanguns** [comment]
Testing always is fine! good job!

**Comment by jmcdo29** [comment]
I made a big change to the file structure of each package so that now tests and source files are separated. I feel it will bring a cleaner structure overall to the project so that we aren't looking through both source and tests at the same time. 

I'm aware of the SonarCloud failure due to duplicate code. As it's between spec files, I'll probably tell SonarCloud to ignore it and move on, but I'm thinking of making a `tools` directory to help cut down on duplication, as a lot of these test files are going to look super similar when it comes to unit tests. The real fun will be writing the integration tests :smile:

**Comment by jmcdo29** [comment]
I'll keep this open till this evening to get some feedback. Let me know if there's a concern about the setup

**Review by jeffminsungkim — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
