### PR TITLE
feat(logger): add 'levelKey' option

### LINKED ISSUE #553: [Parser]: Log Level Label
## Feature Request
This is a direct follow up of #535. I forgot that the cloud providers, e.g. google, sometimes do not use level but severity as the key for the level. Hence, for Staackdriver to pick up the logs, the level value must be put into the severity field.

## Is your feature request related to a problem? Please describe.

Stackdriver does not pick up the level.

## Describe the solution you'd like

Either a config option to set the key name like a "key map" or a function that allows modification of the json before it is written would be great.

### PR DESCRIPTION
**Pull request by psteinroe**
closes #553

### CODE REVIEW

**Review by jmcdo29 — APPROVED** [review]
LGTM. Glad this was an easy fix too. Thanks for adding in the changeset as well

**Comment by jmcdo29** [comment]
I'll look into why the packages have major bumps instead of minor or patch level. Thanks again!

**Comment by psteinroe** [comment]
Thanks for your effort! 🙏🏼

**Comment by psteinroe** [comment]
Let me know if I should reopen because of the changeset problem! :)

**Comment by jmcdo29** [comment]
Sorry about the delay. Been on vacation. I'll try to get this merged this week, hopefully sooner rather than later

**Comment by psteinroe** [comment]
No worries, enjoy your vacation! :)

**Comment by jmcdo29** [comment]
Huh, looks like the force push didn't do what I wanted it to. I'll get that fixed

**Pull request closed without merging**
